### ISSUE TITLE
Build instructions fail on `make`

### ISSUE THREAD

**Issue by moradology** [zerebubuth/planet-dump-ng#19]
Following the instructions on the README was straightforward enough but ended up failing in a way that's hard for me to make heads or tails of as a newcomer to this project. To replicate these difficulties, use the Dockerfile below with these arguments:
`docker build . --build-arg pdng=1.1.3`
`docker build . --build-arg pdng=1.1.4`
```
FROM ubuntu:18.04

ARG pdng=1.1.4

# update and add package to avoid apt warning
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

# utility libs
RUN apt-get install -y curl

# build requirements
RUN apt-get install -y build-essential automake autoconf \
  libxml2-dev libboost-dev libboost-program-options-dev \
  libboost-date-time-dev libboost-filesystem-dev \
  libboost-thread-dev libboost-iostreams-dev \
  libosmpbf-dev osmpbf-bin libprotobuf-dev pkg-config

# get/compile PlanetDumpNG
WORKDIR /root/
RUN curl -L https://github.com/zerebubuth/planet-dump-ng/archive/v${pdng}.tar.gz --output v${pdng}.tar.gz
RUN tar xvf v${pdng}.tar.gz

WORKDIR /root/planet-dump-ng-${pdng}/
RUN ./autogen.sh
RUN ./configure
RUN make  # failure :(
```

**Comment by moradology** [comment]
My container's final words:
```
Making all in src
make[1]: Entering directory '/root/planet-dump-ng-1.1.3/src'
  CXX      changeset_filter.o
  CXX      changeset_map.o
  CXX      copy_elements.o
copy_elements.cpp: In instantiation of 'bool {anonymous}::is_redacted(const T&) [with T = node]':
copy_elements.cpp:204:23:   required from 'void {anonymous}::extract_element({anonymous}::thread_writer<T>&) [with T = node]'
copy_elements.cpp:318:23:   required from 'void reader_thread(int, boost::exception_ptr, boost::shared_ptr<{anonymous}::control_block<T> >) [with T = node]'
copy_elements.cpp:350:66:   required from 'void run_threads(std::vector<boost::shared_ptr<output_writer> >) [with T = node]'
copy_elements.cpp:385:79:   required from here
copy_elements.cpp:173:48: error: cannot convert 'const boost::optional<long int>' to 'bool' in return
 inline bool is_redacted(const T &t) { return t.redaction_id; }
                                                ^~~~~~~~~~~~
copy_elements.cpp: In instantiation of 'bool {anonymous}::is_redacted(const T&) [with T = way]':
copy_elements.cpp:204:23:   required from 'void {anonymous}::extract_element({anonymous}::thread_writer<T>&) [with T = way]'
copy_elements.cpp:318:23:   required from 'void reader_thread(int, boost::exception_ptr, boost::shared_ptr<{anonymous}::control_block<T> >) [with T = way]'
copy_elements.cpp:350:66:   required from 'void run_threads(std::vector<boost::shared_ptr<output_writer> >) [with T = way]'
copy_elements.cpp:386:78:   required from here
copy_elements.cpp:173:48: error: cannot convert 'const boost::optional<long int>' to 'bool' in return
copy_elements.cpp: In instantiation of 'bool {anonymous}::is_redacted(const T&) [with T = relation]':
copy_elements.cpp:204:23:   required from 'void {anonymous}::extract_element({anonymous}::thread_writer<T>&) [with T = relation]'
copy_elements.cpp:318:23:   required from 'void reader_thread(int, boost::exception_ptr, boost::shared_ptr<{anonymous}::control_block<T> >) [with T = relation]'
copy_elements.cpp:350:66:   required from 'void run_threads(std::vector<boost::shared_ptr<output_writer> >) [with T = relation]'
copy_elements.cpp:387:83:   required from here
copy_elements.cpp:173:48: error: cannot convert 'const boost::optional<long int>' to 'bool' in return
Makefile:422: recipe for target 'copy_elements.o' failed
make[1]: *** [copy_elements.o] Error 1
make[1]: Leaving directory '/root/planet-dump-ng-1.1.3/src'
Makefile:603: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by zerebubuth** [comment]
I think this is caused by a more recent compiler dropping support for implicit conversions to bool in the return statement.

I've pushed a [`v1.1.5`](https://github.com/zerebubuth/planet-dump-ng/releases/tag/v1.1.5) up, which is just #17 and #18, plus the change to explicitly cast to `bool`. Apologies for not testing it; my attempts to test have failed because docker just hangs and virtualbox now crashes my machine (they both worked fine before Christmas!). :sob: 

Please let me know whether you're able to build the new release.

**Comment by zerebubuth** [comment]
NB: If you really need v1.1.4 or previous, it might be worth trying to build with an Ubuntu 16.04 image and compiler.

**Comment by moradology** [comment]
I believe 1.1.5 solves the issue entirely. Thanks for cutting such a quick release!

**Comment by zerebubuth** [comment]
Thanks very much for pointing out the problem!
